# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d24c651568c170e810753786917c8a3c647598141d5da928cc7855f13f566329f3a0ac7f50f3d37a2ee5d983d6ccef1a5a585b80f4917f8643a4ca3e5b9ab64

test:
  secret_key_base: 870e2f87dd8732c8dfb769aba8ee6149a17e4a66738bf41d32161d7efa2be4b1a1453b911ae5b5dacfbad2746a68a0af4d9eefbe2ca74c88d40be388a52a4945

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
